language: java

services:
- docker

script:
- gradle build
- cd tutoringservice-frontend
- heroku git:remote --app tutoringservice321-frontend
- heroku container:login
- heroku container:push web
- heroku container:release web
- cd ../TutoringService321-Backend
- git add .
- git commit -am "deployment"
- git push heroku master
